name: XAUUSD Telegram

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  send-price:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: python -m pip install requests

      - name: Send XAUUSD price
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: python bot.py
